export const address = {
  city: '中央区',
  pref: '東京都',
  town: '京橋',
  zipcode: '104-0031',
};

export const addresses = [
  {
    zipcode: '734-0001',
    pref: '広島県',
    city: '広島市南区',
    town: '出汐',
  },
  {
    zipcode: '734-0002',
    pref: '広島県',
    city: '広島市南区',
    town: '西旭町',
  },
  {
    zipcode: '734-0003',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品東',
  },
  {
    zipcode: '734-0004',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品神田',
  },
  {
    zipcode: '734-0005',
    pref: '広島県',
    city: '広島市南区',
    town: '翠',
  },
  {
    zipcode: '734-0006',
    pref: '広島県',
    city: '広島市南区',
    town: '西翠町',
  },
  {
    zipcode: '734-0007',
    pref: '広島県',
    city: '広島市南区',
    town: '皆実町',
  },
  {
    zipcode: '734-0011',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品海岸',
  },
  {
    zipcode: '734-0012',
    pref: '広島県',
    city: '広島市南区',
    town: '元宇品町',
  },
  {
    zipcode: '734-0013',
    pref: '広島県',
    city: '広島市南区',
    town: '出島',
  },
  {
    zipcode: '734-0014',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品西',
  },
  {
    zipcode: '734-0015',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品御幸',
  },
  {
    zipcode: '734-0016',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品町',
  },
  {
    zipcode: '734-0017',
    pref: '広島県',
    city: '広島市南区',
    town: '似島町',
  },
  {
    zipcode: '734-0021',
    pref: '広島県',
    city: '広島市南区',
    town: '上東雲町',
  },
  {
    zipcode: '734-0022',
    pref: '広島県',
    city: '広島市南区',
    town: '東雲',
  },
  {
    zipcode: '734-0023',
    pref: '広島県',
    city: '広島市南区',
    town: '東雲本町',
  },
  {
    zipcode: '734-0024',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保新町',
  },
  {
    zipcode: '734-0025',
    pref: '広島県',
    city: '広島市南区',
    town: '東本浦町',
  },
  {
    zipcode: '734-0026',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保',
  },
  {
    zipcode: '734-0027',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保南',
  },
  {
    zipcode: '734-0031',
    pref: '広島県',
    city: '広島市南区',
    town: '日宇那町',
  },
  {
    zipcode: '734-0032',
    pref: '広島県',
    city: '広島市南区',
    town: '楠那町',
  },
  {
    zipcode: '734-0033',
    pref: '広島県',
    city: '広島市南区',
    town: '丹那新町',
  },
  {
    zipcode: '734-0034',
    pref: '広島県',
    city: '広島市南区',
    town: '丹那町',
  },
  {
    zipcode: '734-0035',
    pref: '広島県',
    city: '広島市南区',
    town: '山城町',
  },
  {
    zipcode: '734-0036',
    pref: '広島県',
    city: '広島市南区',
    town: '旭',
  },
  {
    zipcode: '734-0037',
    pref: '広島県',
    city: '広島市南区',
    town: '霞',
  },
  {
    zipcode: '734-0041',
    pref: '広島県',
    city: '広島市南区',
    town: '黄金山町',
  },
];
