export const address = [
  {
    city: '中央区',
    pref: '東京都',
    town: '京橋',
    zipcode: '1040031',
  },
];

export const addresses = [
  {
    zipcode: '7340001',
    pref: '広島県',
    city: '広島市南区',
    town: '出汐',
  },
  {
    zipcode: '7340002',
    pref: '広島県',
    city: '広島市南区',
    town: '西旭町',
  },
  {
    zipcode: '7340003',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品東',
  },
  {
    zipcode: '7340004',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品神田',
  },
  {
    zipcode: '7340005',
    pref: '広島県',
    city: '広島市南区',
    town: '翠',
  },
  {
    zipcode: '7340006',
    pref: '広島県',
    city: '広島市南区',
    town: '西翠町',
  },
  {
    zipcode: '7340007',
    pref: '広島県',
    city: '広島市南区',
    town: '皆実町',
  },
  {
    zipcode: '7340011',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品海岸',
  },
  {
    zipcode: '7340012',
    pref: '広島県',
    city: '広島市南区',
    town: '元宇品町',
  },
  {
    zipcode: '7340013',
    pref: '広島県',
    city: '広島市南区',
    town: '出島',
  },
  {
    zipcode: '7340014',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品西',
  },
  {
    zipcode: '7340015',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品御幸',
  },
  {
    zipcode: '7340016',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品町',
  },
  {
    zipcode: '7340017',
    pref: '広島県',
    city: '広島市南区',
    town: '似島町',
  },
  {
    zipcode: '7340021',
    pref: '広島県',
    city: '広島市南区',
    town: '上東雲町',
  },
  {
    zipcode: '7340022',
    pref: '広島県',
    city: '広島市南区',
    town: '東雲',
  },
  {
    zipcode: '7340023',
    pref: '広島県',
    city: '広島市南区',
    town: '東雲本町',
  },
  {
    zipcode: '7340024',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保新町',
  },
  {
    zipcode: '7340025',
    pref: '広島県',
    city: '広島市南区',
    town: '東本浦町',
  },
  {
    zipcode: '7340026',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保',
  },
  {
    zipcode: '7340027',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保南',
  },
  {
    zipcode: '7340031',
    pref: '広島県',
    city: '広島市南区',
    town: '日宇那町',
  },
  {
    zipcode: '7340032',
    pref: '広島県',
    city: '広島市南区',
    town: '楠那町',
  },
  {
    zipcode: '7340033',
    pref: '広島県',
    city: '広島市南区',
    town: '丹那新町',
  },
  {
    zipcode: '7340034',
    pref: '広島県',
    city: '広島市南区',
    town: '丹那町',
  },
  {
    zipcode: '7340035',
    pref: '広島県',
    city: '広島市南区',
    town: '山城町',
  },
  {
    zipcode: '7340036',
    pref: '広島県',
    city: '広島市南区',
    town: '旭',
  },
  {
    zipcode: '7340037',
    pref: '広島県',
    city: '広島市南区',
    town: '霞',
  },
  {
    zipcode: '7340041',
    pref: '広島県',
    city: '広島市南区',
    town: '黄金山町',
  },
  {
    zipcode: '7320001',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂惣田',
  },
  {
    zipcode: '7320002',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂山根',
  },
  {
    zipcode: '7320003',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂中町',
  },
  {
    zipcode: '7320004',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂山崎町',
  },
  {
    zipcode: '7320005',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂桜東町',
  },
  {
    zipcode: '7320006',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂桜西町',
  },
  {
    zipcode: '7320007',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂桜上町',
  },
  {
    zipcode: '7320008',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂くるめ木',
  },
  {
    zipcode: '7320009',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂千足',
  },
  {
    zipcode: '7320011',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂町',
  },
  {
    zipcode: '7320012',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂新町',
  },
  {
    zipcode: '7320013',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂南',
  },
  {
    zipcode: '7320014',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂大上',
  },
  {
    zipcode: '7320015',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂城山町',
  },
  {
    zipcode: '7320016',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂出江',
  },
  {
    zipcode: '7320017',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂数甲',
  },
  {
    zipcode: '7320018',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂長尾台',
  },
  {
    zipcode: '7320021',
    pref: '広島県',
    city: '広島市東区',
    town: '中山新町',
  },
  {
    zipcode: '7320022',
    pref: '広島県',
    city: '広島市東区',
    town: '中山鏡が丘',
  },
  {
    zipcode: '7320023',
    pref: '広島県',
    city: '広島市東区',
    town: '中山東',
  },
  {
    zipcode: '7320024',
    pref: '広島県',
    city: '広島市東区',
    town: '中山南',
  },
  {
    zipcode: '7320025',
    pref: '広島県',
    city: '広島市東区',
    town: '中山西',
  },
  {
    zipcode: '7320026',
    pref: '広島県',
    city: '広島市東区',
    town: '中山中町',
  },
  {
    zipcode: '7320027',
    pref: '広島県',
    city: '広島市東区',
    town: '中山上',
  },
  {
    zipcode: '7320028',
    pref: '広島県',
    city: '広島市東区',
    town: '中山北町',
  },
  {
    zipcode: '7320029',
    pref: '広島県',
    city: '広島市東区',
    town: '福田',
  },
  {
    zipcode: '7320031',
    pref: '広島県',
    city: '広島市東区',
    town: '馬木',
  },
  {
    zipcode: '7320032',
    pref: '広島県',
    city: '広島市東区',
    town: '上温品',
  },
  {
    zipcode: '7320033',
    pref: '広島県',
    city: '広島市東区',
    town: '温品',
  },
  {
    zipcode: '7320034',
    pref: '広島県',
    city: '広島市東区',
    town: '温品町',
  },
  {
    zipcode: '7320035',
    pref: '広島県',
    city: '広島市東区',
    town: '馬木町',
  },
  {
    zipcode: '7320036',
    pref: '広島県',
    city: '広島市東区',
    town: '福田町',
  },
  {
    zipcode: '7320041',
    pref: '広島県',
    city: '広島市東区',
    town: '矢賀町',
  },
  {
    zipcode: '7320042',
    pref: '広島県',
    city: '広島市東区',
    town: '矢賀',
  },
  {
    zipcode: '7320043',
    pref: '広島県',
    city: '広島市東区',
    town: '東山町',
  },
  {
    zipcode: '7320044',
    pref: '広島県',
    city: '広島市東区',
    town: '矢賀新町',
  },
  {
    zipcode: '7320045',
    pref: '広島県',
    city: '広島市東区',
    town: '曙',
  },
  {
    zipcode: '7320046',
    pref: '広島県',
    city: '広島市東区',
    town: '尾長東',
  },
  {
    zipcode: '7320047',
    pref: '広島県',
    city: '広島市東区',
    town: '尾長西',
  },
  {
    zipcode: '7320048',
    pref: '広島県',
    city: '広島市東区',
    town: '山根町',
  },
  {
    zipcode: '7320049',
    pref: '広島県',
    city: '広島市東区',
    town: '尾長町',
  },
  {
    zipcode: '7320051',
    pref: '広島県',
    city: '広島市東区',
    town: '光が丘',
  },
  {
    zipcode: '7320052',
    pref: '広島県',
    city: '広島市東区',
    town: '光町',
  },
  {
    zipcode: '7320053',
    pref: '広島県',
    city: '広島市東区',
    town: '若草町',
  },
  {
    zipcode: '7320054',
    pref: '広島県',
    city: '広島市東区',
    town: '愛宕町',
  },
  {
    zipcode: '7320055',
    pref: '広島県',
    city: '広島市東区',
    town: '東蟹屋町',
  },
  {
    zipcode: '7320056',
    pref: '広島県',
    city: '広島市東区',
    town: '上大須賀町',
  },
  {
    zipcode: '7320057',
    pref: '広島県',
    city: '広島市東区',
    town: '二葉の里',
  },
  {
    zipcode: '7320061',
    pref: '広島県',
    city: '広島市東区',
    town: '牛田山',
  },
  {
    zipcode: '7320062',
    pref: '広島県',
    city: '広島市東区',
    town: '牛田早稲田',
  },
];
