export const address = [
  {
    city: '中央区',
    pref: '東京都',
    town: '京橋',
    zipcode: '104-0031',
  },
];

export const addresses = [
  {
    zipcode: '734-0001',
    pref: '広島県',
    city: '広島市南区',
    town: '出汐',
  },
  {
    zipcode: '734-0002',
    pref: '広島県',
    city: '広島市南区',
    town: '西旭町',
  },
  {
    zipcode: '734-0003',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品東',
  },
  {
    zipcode: '734-0004',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品神田',
  },
  {
    zipcode: '734-0005',
    pref: '広島県',
    city: '広島市南区',
    town: '翠',
  },
  {
    zipcode: '734-0006',
    pref: '広島県',
    city: '広島市南区',
    town: '西翠町',
  },
  {
    zipcode: '734-0007',
    pref: '広島県',
    city: '広島市南区',
    town: '皆実町',
  },
  {
    zipcode: '734-0011',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品海岸',
  },
  {
    zipcode: '734-0012',
    pref: '広島県',
    city: '広島市南区',
    town: '元宇品町',
  },
  {
    zipcode: '734-0013',
    pref: '広島県',
    city: '広島市南区',
    town: '出島',
  },
  {
    zipcode: '734-0014',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品西',
  },
  {
    zipcode: '734-0015',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品御幸',
  },
  {
    zipcode: '734-0016',
    pref: '広島県',
    city: '広島市南区',
    town: '宇品町',
  },
  {
    zipcode: '734-0017',
    pref: '広島県',
    city: '広島市南区',
    town: '似島町',
  },
  {
    zipcode: '734-0021',
    pref: '広島県',
    city: '広島市南区',
    town: '上東雲町',
  },
  {
    zipcode: '734-0022',
    pref: '広島県',
    city: '広島市南区',
    town: '東雲',
  },
  {
    zipcode: '734-0023',
    pref: '広島県',
    city: '広島市南区',
    town: '東雲本町',
  },
  {
    zipcode: '734-0024',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保新町',
  },
  {
    zipcode: '734-0025',
    pref: '広島県',
    city: '広島市南区',
    town: '東本浦町',
  },
  {
    zipcode: '734-0026',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保',
  },
  {
    zipcode: '734-0027',
    pref: '広島県',
    city: '広島市南区',
    town: '仁保南',
  },
  {
    zipcode: '734-0031',
    pref: '広島県',
    city: '広島市南区',
    town: '日宇那町',
  },
  {
    zipcode: '734-0032',
    pref: '広島県',
    city: '広島市南区',
    town: '楠那町',
  },
  {
    zipcode: '734-0033',
    pref: '広島県',
    city: '広島市南区',
    town: '丹那新町',
  },
  {
    zipcode: '734-0034',
    pref: '広島県',
    city: '広島市南区',
    town: '丹那町',
  },
  {
    zipcode: '734-0035',
    pref: '広島県',
    city: '広島市南区',
    town: '山城町',
  },
  {
    zipcode: '734-0036',
    pref: '広島県',
    city: '広島市南区',
    town: '旭',
  },
  {
    zipcode: '734-0037',
    pref: '広島県',
    city: '広島市南区',
    town: '霞',
  },
  {
    zipcode: '734-0041',
    pref: '広島県',
    city: '広島市南区',
    town: '黄金山町',
  },
  {
    zipcode: '732-0001',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂惣田',
  },
  {
    zipcode: '732-0002',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂山根',
  },
  {
    zipcode: '732-0003',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂中町',
  },
  {
    zipcode: '732-0004',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂山崎町',
  },
  {
    zipcode: '732-0005',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂桜東町',
  },
  {
    zipcode: '732-0006',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂桜西町',
  },
  {
    zipcode: '732-0007',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂桜上町',
  },
  {
    zipcode: '732-0008',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂くるめ木',
  },
  {
    zipcode: '732-0009',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂千足',
  },
  {
    zipcode: '732-0011',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂町',
  },
  {
    zipcode: '732-0012',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂新町',
  },
  {
    zipcode: '732-0013',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂南',
  },
  {
    zipcode: '732-0014',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂大上',
  },
  {
    zipcode: '732-0015',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂城山町',
  },
  {
    zipcode: '732-0016',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂出江',
  },
  {
    zipcode: '732-0017',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂数甲',
  },
  {
    zipcode: '732-0018',
    pref: '広島県',
    city: '広島市東区',
    town: '戸坂長尾台',
  },
  {
    zipcode: '732-0021',
    pref: '広島県',
    city: '広島市東区',
    town: '中山新町',
  },
  {
    zipcode: '732-0022',
    pref: '広島県',
    city: '広島市東区',
    town: '中山鏡が丘',
  },
  {
    zipcode: '732-0023',
    pref: '広島県',
    city: '広島市東区',
    town: '中山東',
  },
  {
    zipcode: '732-0024',
    pref: '広島県',
    city: '広島市東区',
    town: '中山南',
  },
  {
    zipcode: '732-0025',
    pref: '広島県',
    city: '広島市東区',
    town: '中山西',
  },
  {
    zipcode: '732-0026',
    pref: '広島県',
    city: '広島市東区',
    town: '中山中町',
  },
  {
    zipcode: '732-0027',
    pref: '広島県',
    city: '広島市東区',
    town: '中山上',
  },
  {
    zipcode: '732-0028',
    pref: '広島県',
    city: '広島市東区',
    town: '中山北町',
  },
  {
    zipcode: '732-0029',
    pref: '広島県',
    city: '広島市東区',
    town: '福田',
  },
  {
    zipcode: '732-0031',
    pref: '広島県',
    city: '広島市東区',
    town: '馬木',
  },
  {
    zipcode: '732-0032',
    pref: '広島県',
    city: '広島市東区',
    town: '上温品',
  },
  {
    zipcode: '732-0033',
    pref: '広島県',
    city: '広島市東区',
    town: '温品',
  },
  {
    zipcode: '732-0034',
    pref: '広島県',
    city: '広島市東区',
    town: '温品町',
  },
  {
    zipcode: '732-0035',
    pref: '広島県',
    city: '広島市東区',
    town: '馬木町',
  },
  {
    zipcode: '732-0036',
    pref: '広島県',
    city: '広島市東区',
    town: '福田町',
  },
  {
    zipcode: '732-0041',
    pref: '広島県',
    city: '広島市東区',
    town: '矢賀町',
  },
  {
    zipcode: '732-0042',
    pref: '広島県',
    city: '広島市東区',
    town: '矢賀',
  },
  {
    zipcode: '732-0043',
    pref: '広島県',
    city: '広島市東区',
    town: '東山町',
  },
  {
    zipcode: '732-0044',
    pref: '広島県',
    city: '広島市東区',
    town: '矢賀新町',
  },
  {
    zipcode: '732-0045',
    pref: '広島県',
    city: '広島市東区',
    town: '曙',
  },
  {
    zipcode: '732-0046',
    pref: '広島県',
    city: '広島市東区',
    town: '尾長東',
  },
  {
    zipcode: '732-0047',
    pref: '広島県',
    city: '広島市東区',
    town: '尾長西',
  },
  {
    zipcode: '732-0048',
    pref: '広島県',
    city: '広島市東区',
    town: '山根町',
  },
  {
    zipcode: '732-0049',
    pref: '広島県',
    city: '広島市東区',
    town: '尾長町',
  },
  {
    zipcode: '732-0051',
    pref: '広島県',
    city: '広島市東区',
    town: '光が丘',
  },
  {
    zipcode: '732-0052',
    pref: '広島県',
    city: '広島市東区',
    town: '光町',
  },
  {
    zipcode: '732-0053',
    pref: '広島県',
    city: '広島市東区',
    town: '若草町',
  },
  {
    zipcode: '732-0054',
    pref: '広島県',
    city: '広島市東区',
    town: '愛宕町',
  },
  {
    zipcode: '732-0055',
    pref: '広島県',
    city: '広島市東区',
    town: '東蟹屋町',
  },
  {
    zipcode: '732-0056',
    pref: '広島県',
    city: '広島市東区',
    town: '上大須賀町',
  },
  {
    zipcode: '732-0057',
    pref: '広島県',
    city: '広島市東区',
    town: '二葉の里',
  },
  {
    zipcode: '732-0061',
    pref: '広島県',
    city: '広島市東区',
    town: '牛田山',
  },
  {
    zipcode: '732-0062',
    pref: '広島県',
    city: '広島市東区',
    town: '牛田早稲田',
  },
];
